# Site settings
title: Guía de Estilos - Wall Arquitectura & Diseño
email: contacto@wallarquitectura.com
description: Brand Guidelines | Wall Arquitectura & Diseño
baseurl: '/wall-styleguide'
twitter_username: wall_arq
paginate: 4

# Build settings
markdown: kramdown
permalink: /:title

group : jekyll_plugins do
   gem [ handelize ]
 end
 
gems: [ jekyll-paginate ]

#Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Guil Hernandez"
      categories: "author"
      layout: "post"
      comments: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_with_nav"
      
   

